Benchmark parametrisation
tesonep/benchy pull request #15
Opened 2023-05-05 14:48 UTC by DurieuxPol

Added the possibility to specify a directory other than /benchs to run the benchmarks from, in a similar way to how the number of iterations can be changed.
Also includes a workflow and a /test to run the test, as well as a bit of refactoring of how benchmarks are run.

2023-05-05 15:03 UTC, jordanmontt commented
The Ci is failing with: `tests/benchParamTest.sh: not found`

2023-05-05 15:05 UTC, guillep commented
> The Ci is failing with: `tests/benchParamTest.sh: not found`

This is probably a bug in the path used in the github action.

2023-05-05 15:07 UTC, guillep requested changes

2023-05-05 15:07 UTC, guillep commented on .github/workflows/benchparam.yml
> +        cli: "tests/benchParamTest.sh"
```suggestion
        cli: "./test/benchParamTest.sh"
```

2023-05-05 15:07 UTC, guillep commented on .github/workflows/benchparam.yml
> +        cli: "tests/benchParamTest.sh"
There is a typo in the directory name

2023-05-05 15:09 UTC, guillep requested changes
the sh file has no execution permissions

2023-05-05 15:09 UTC, guillep commented on .github/workflows/benchparam.yml
> +        cli: "./test/benchParamTest.sh"
```suggestion
        cli: "bash ./test/benchParamTest.sh"
```

2023-05-05 15:10 UTC, jordanmontt commented
Nice, now we have an actual test failing

2023-05-09 22:10 UTC, guillep commented
Tests are green! The smoke tests timeout because the druid build is super slow...

2023-05-09 22:10 UTC, merged

2023-05-09 22:10 UTC, guillep commented
Thanks @DurieuxPol !